# Generated by Django 4.2.2 on 2023-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
